# Additional site Params
# -------------------------
# Comprehensive list of netlify's CSP content contexts:
#  --> child-src, default-src, connect-src, font-src, frame-src, img-src, manifest-src
# media-src, object-src, prefetch-src, script-src, script-srcElem, script-srcAttr,
# style-src, style-srcElem, style-srcAttr, worker-src

[modules]
    [modules.timelinejs]
        integration = "optional"
        state = "async"
        category = "other"
    [modules.timelinejs.csp]
        style-src = ["www.youtube.com"]
        font-src = ["fonts.gstatic.com"]
        frame-src = [
            "player.cloudinary.com",
            "www.youtube-nocookie.com",
            "www.youtube.com",
            "www.vimeo.com",
            "*.x.com",
            "*.twitter.com",
            "*.wikipedia.com",
            "play.spotify.com",
            "maps.google.com",
            "www.google.com",
            "docs.google.com"
        ]
        img-src = [
            "data:",
            "*.imgix.net",
            "*.imagekit.io",
            "*.cloudinary.com",
            "i.ytimg.com",
            "*.x.com",
            "*.twitter.com",
            "www.youtube.com",
            "instagram.com",
            "imgur.com",
            "www.flickr.com",
            "docs.google.com",
            "www.google.com"
        ]
        media-src = [
            "vimeo.com",
            "www.dailymotion.com",
            "*.x.com",
            "play.spotify.com",
            "soundcloud.com",
            "www.google.com",
            "docs.google.com"
        ]

[debugging]
    showJS = true
    showSCSS = true
