[module]
  [module.hugoVersion]
    extended = true
    min = "0.110.0"
    max = ""
  [[module.mounts]]
    source = "dist/js/timeline.js"
    target = "assets/js/modules/timeline/timeline.js"
  [[module.mounts]]
    source = "dist"
    target = "assets/scss"
    includeFiles = [
      "timeline.scss",
      "fonts.scss"
    ]
  [[module.mounts]]
    source = "dist/locale"
    target = "assets/js/modules/timeline/locale"
  [[module.mounts]]
    source = "dist/fonts"
    target = "static/fonts"
  [[module.mounts]]
    source = "dist/icons"
    target = "static/icons"
  [[module.mounts]]
    source = 'layouts'
    target = 'layouts'
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = 'static'
    target = 'static'
  [[module.imports]]
    path = "github.com/gethinode/mod-utils/v2"
