[module]
  [module.hugoVersion]
    extended = true
    min = "0.110.0"
    max = ""
  [[module.mounts]]
    source = "dist/js/timeline.js"
    target = "assets/js/modules/timelinejs/timeline.js"
  [[module.mounts]]
    source = "dist"
    target = "static"
    includeFiles = [
      "timeline.scss",
      "font.default.scss",
      "tl-icons.woff2"
    ]
  [[module.mounts]]
    source = "dist/timelinejs.html"
    target = "layouts/shortcodes/modules/timelinejs/timelinejs.html"
  [[module.mounts]]
    source = 'layouts'
    target = 'layouts'
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = 'static'
    target = 'static'