[module]
  [module.hugoVersion]
    extended = true
    min = "0.110.0"
    max = ""
  [[module.mounts]]
    source = "dist/js/timeline.js"
    target = "assets/js/modules/timelinejs"
    includeFiles = "timeline.js"
  [[module.mounts]]
    source = "dist/scss/timeline.scss"
    target = "assets/scss/timeline.scss"
  [[module.mounts]]
    source = "dist/scss/timeline.css.map"
    target = "assets/scss/modules/timelinejs/timeline.css.map"
  [[module.mounts]]
    source = "dist/scss/font.default.scss"
    target = "assets/scss/modules/timelinejs/font.default.scss"
  [[module.mounts]]
    source = "dist/icons/tl-icons.woff2"
    target = "static/tl-icons.woff2"
  [[module.mounts]]
    source = 'layouts'
    target = 'layouts'
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = 'static'
    target = 'static'
