[markup.goldmark.renderer]
  unsafe = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.110.0"
    max = ""
  [[module.mounts]]
    source = 'layouts'
    target = 'layouts'
    excludeSCSS = true
