[markup.goldmark.renderer]
  unsafe = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.110.0"
    max = ""
  [[module.mounts]]
    source = "dist/js/timeline.js"
    target = "static/js/timeline.js"
  [[module.mounts]]
    source = "dist/scss/modules/timelinejs"
    target = "assets/scss/modules/timelinejs"
  [[module.mounts]]
    source = "dist/icons"
    target = "static/icons"
  [[module.mounts]]
    source = 'layouts'
    target = 'layouts'
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    source = 'static'
    target = 'static'