baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Test site for mod-timelinejs3'

[main.build]
  transpiler = "dartsass"

[markup.goldmark.renderer]
  unsafe = true

[markup.goldmark.parser.attribute]
  block = true

[module]
  # Build and serve using local mod-timelinejs3 clone declared in the named Hugo workspace:
  workspace = "mod-timelinejs3.work"
  replacements = "github.com/anoduck/mod-timelinejs3 -> ../.."

  [[module.imports]]
    path = "github.com/anoduck/mod-timelinejs3"
