baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Test site for mod-timelinejs3'

[module]
  # Build and serve using local mod-timelinejs3 clone declared in the named Hugo workspace:
  workspace = "mod-template.work"
  replacements = "github.com/anoduck/mod-timelinejs3 -> ../.."
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.imports]]
    path = "github.com/anoduck/mod-timelinejs3"
  [[module.imports.mounts]]
    source = "dist/scss/timeline.scss"
    target = "static/timeline.css"
  [[module.imports.mounts]]
    source = "dist/scss/timeline.css.map"
    target = "static/timeline.css.map"
  [[module.imports.mounts]]
    source = "dist/scss/font.default.scss"
    target = "static/font.default.css"
  [[module.imports.mounts]]
    source = "dist/js/timeline.js"
    target = "static/js/timeline.js"
  [[module.imports.mounts]]
    source = "dist/icons/tl-icons.woff2"
    target = "static/tl-icons.woff2"
  [[module.imports.mounts]]
    source = "layouts"
    target = "layouts"
