baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Test site for mod-timelinejs'

[main]
  enableDarkMode = true

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.parser.attribute]
block = true

[module]
  # Build and serve using local mod-timelinejs clone declared in the named Hugo workspace:
  workspace = "mod-timelinejs.work"
  replacements = "github.com/anoduck/mod-timelinejs -> ../.."

  [[module.imports]]
    path = "github.com/anoduck/mod-timelinejs"
